### ISSUE TITLE
Chrome PDF export landscape orientation missing

### ISSUE THREAD

**Issue by mrtnbrst** [isanchop/stuhack#20]
I tried printing a document in landscape mode, but chrome didn't provide the option.
I found [this](https://support.google.com/chrome/thread/3101500?hl=en&msgid=95601075) thread suggesting using the style 
```css   
@page {
        size: auto;
    }
```
The option for the landscape mode shows up when applied as described in the linked post.
<br>
[Here](https://github.com/isanchop/stuhack/blob/84a6931a2ffa61431cd96dfecb101bbb409b73d2/doc-viewer.js#L40) you are using the style
```css   
@page {
        size: A5;
    }
```
, which currently doesn't work.
Should I open a pull request or is there a reason for A5 being used as size?
